name: Build Windows Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build Windows .exe
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: install rust
      uses: dtolnay/rust-toolchain@stable

    - name: Compile
      uses: rust-build/rust-build.action@v1.4.5
      with:
        RUSTTARGET: x86_64-pc-windows-gnu
        UPLOAD_MODE: none

    - name: Upload Windows release binary
      uses: softprops/action-gh-release@v2
      with:
        files: target/x86_64-pc-windows-gnu/release/path-length-checker.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
